name: DalboUtil
version: @version@
main: space.mori.dalboutil.DalboUtil
api-version: 1.14
depend:
authors:
  - dalbodeule
commands:
  party:
    permission: dalboutil.party
permissions:
  dalboutil.party:
    default: true